import React from "react";

export class Counter extends React.Component {
    state = {
        counter: 0,
    }

    constructor(props) {
        super(props);

        setInterval(() => {
            // this.setState(previousState => ({
            //     counter: previousState + 1          FUNCTION/CALLBACK SETSTATE
            // })
            // {
            //     counter: this.state.counter + 1,     OBJECT SETSTATE
            // });
        }, 1000);
    }

    render() {
        return (
          <>
            <h1>
                Counter: {this.state.counter}
            </h1>
          </>
        );
    }
}

// BOTH CAN BE USED DEPENDS... IF IT IS A MUST TO GET THE PREVIOUS VALUE OF THE SETSTATE WE SHALL USE THE FUNCTION/CALLBACK SETSTATE ELSE THE OBJECT THAT WON'T CARE ABOUT THE PREVIOUS VALUE
// BOTH CAN BE USED DEPENDS... IF IT IS A MUST TO GET THE PREVIOUS VALUE OF THE SETSTATE WE SHALL USE THE FUNCTION/CALLBACK SETSTATE ELSE THE OBJECT THAT WON'T CARE ABOUT THE PREVIOUS VALUE
// BOTH CAN BE USED DEPENDS... IF IT IS A MUST TO GET THE PREVIOUS VALUE OF THE SETSTATE WE SHALL USE THE FUNCTION/CALLBACK SETSTATE ELSE THE OBJECT THAT WON'T CARE ABOUT THE PREVIOUS VALUE
// BOTH CAN BE USED DEPENDS... IF IT IS A MUST TO GET THE PREVIOUS VALUE OF THE SETSTATE WE SHALL USE THE FUNCTION/CALLBACK SETSTATE ELSE THE OBJECT THAT WON'T CARE ABOUT THE PREVIOUS VALUE
// BOTH CAN BE USED DEPENDS... IF IT IS A MUST TO GET THE PREVIOUS VALUE OF THE SETSTATE WE SHALL USE THE FUNCTION/CALLBACK SETSTATE ELSE THE OBJECT THAT WON'T CARE ABOUT THE PREVIOUS VALUE